### ISSUE TITLE
Furados máis pequenos?

### ISSUE THREAD

**Issue by procastino** [brico-labs/BATS#8]
Os leds e resistencias quedan moi folgados nos seus furados (os botóns non), se cadra se poderían poñer os furados un chisco máis pequenos?

**Comment by salvari** [comment]
Pois resulta que esta mellora ten moitisima tela, estou a estudiar a documentación de KiCAD pero non parece nada doado.

**Comment by procastino** [comment]
Pois déixaos así, tampouco é grave...

**Comment by salvari** [comment]
Imos poñer furados de 30 mils de diametro

**Comment by salvari** [comment]
Solventado en cc29e5e
